version: '3.8'

services:
  homechef-api:
    container_name: homechef-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    env_file: ./.env  # Path to .env in the root directory
    volumes:
      - ".:/opt/app"
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file: ./.env  # Path to .env in the root directory
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

